services:
  app:
    build: .
    container_name: myapp
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DATABASE_HOST=db
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:16