package main

import (
	"context"
	"log/slog"
	"os"
	"os/signal"
	"syscall"
	"time"

	_ "github.com/Uranury/RBK_finalProject/docs" // This is generated by swag
	"github.com/Uranury/RBK_finalProject/internal/auth"
	"github.com/Uranury/RBK_finalProject/internal/http_server"
)

// @title           CS:GO Skin Marketplace API
// @version         1.0
// @description     A marketplace API for buying and selling CS:GO skins
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

func main() {
	logger := slog.New(slog.NewTextHandler(os.Stdout, nil))

	appDeps, err := InitDeps(logger)
	if err != nil {
		logger.Error("Failed to initialize dependencies", "error", err)
		os.Exit(1)
	}
	auth.NewService(appDeps.cfg.JWTKey)

	server, err := http_server.NewServer(
		appDeps.cfg,
		appDeps.db,
		appDeps.redisClient,
		appDeps.asynqClient,
		logger,
	)
	if err != nil {
		logger.Error("Failed to create http_server", "error", err)
		os.Exit(1)
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// Handle shutdown signals
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, syscall.SIGINT, syscall.SIGTERM)

	// Start http_server in goroutine
	go func() {
		logger.Info("Starting http_server", "port", appDeps.cfg.ListenAddr)
		if err := server.Run(); err != nil {
			logger.Error("Server failed to start", "error", err)
			cancel()
		}
	}()

	select {
	case sig := <-sigChan:
		logger.Info("Received shutdown signal", "signal", sig)
	case <-ctx.Done():
		logger.Info("Context cancelled")
	}

	logger.Info("Shutting down http_server...")
	shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer shutdownCancel()

	if err := server.Shutdown(shutdownCtx); err != nil {
		logger.Error("Server shutdown failed", "error", err)
		os.Exit(1)
	}

	logger.Info("Server stopped gracefully")
}
